---
- name: Install system packages
  apt:
    name: "{{ ubuntu_packages }}"
  when: ansible_os_family == 'Debian'

- name: Python pip package
  apt:
    name: python3-pip
  when: ansible_distribution_version >= '20.04'

- name: Python pip package
  apt:
    name: python-pip
  when: ansible_distribution_version < '20.04'

- import_tasks: nfs.yml
- import_tasks: instantlinux.yml
- import_tasks: samba.yml
- import_tasks: virtualbox.yml
- import_tasks: vsftpd.yml
